//! What one change of the clipboard held, and whether and how history keeps it.
//! Passwords never go in: password managers mark what they copy, following the
//! conventions at nspasteboard.org, and copies from the system's password apps
//! are left out even when unmarked.

use sha2::{Digest, Sha256};

use crate::db::clipboard_history::{ClipboardKind, NewClipboardItem};

/// Past this, a copy is data being moved rather than something to bring back.
const LARGEST_TEXT: usize = 2 * 1024 * 1024;
const LARGEST_IMAGE: usize = 20 * 1024 * 1024;

/// Types an app adds to say "do not keep this": concealed (a password),
/// transient or generated. The unprefixed ones are older apps' own markers.
const PRIVATE_MARKERS: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
    "Pasteboard generator type",
    "net.antelle.keeweb",
];

/// Apps whose copies are secrets whether or not they say so.
const PRIVATE_APPS: &[&str] = &[
    "com.apple.keychainaccess",
    "com.apple.Passwords",
    "com.1password.1password",
    "com.agilebits.onepassword7",
    "com.bitwarden.desktop",
    "org.keepassxc.keepassxc",
];

/// The clipboard's contents after a copy, in the forms history can keep.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Copy {
    /// Every type the copy offered, markers included.
    pub types: Vec<String>,
    pub text: Option<String>,
    pub html: Option<String>,
    pub png: Option<Vec<u8>>,
    /// Paths of copied files, as Finder puts them on the clipboard.
    pub files: Vec<String>,
    pub source_name: Option<String>,
    pub source_bundle: Option<String>,
}

/// The history entry `copy` becomes, or `None` for a copy history must not
/// keep: a private one, an empty one, or one too large.
pub fn to_item(copy: Copy) -> Option<NewClipboardItem> {
    if is_private(&copy) {
        return None;
    }
    let text = copy.text.as_deref().filter(|text| !text.trim().is_empty() && text.len() <= LARGEST_TEXT);
    let png = copy.png.as_deref().filter(|png| !png.is_empty() && png.len() <= LARGEST_IMAGE);
    let (kind, text, html, png) = if !copy.files.is_empty() {
        (ClipboardKind::Files, copy.files.join("\n"), None, None)
    } else if let (Some(png), true) = (png, text.is_none_or(is_link)) {
        // A copied image often brings its address along as text: the image is what was copied.
        (ClipboardKind::Image, String::new(), None, Some(png.to_vec()))
    } else {
        let text = text?;
        let kind = if is_link(text) { ClipboardKind::Link } else { ClipboardKind::Text };
        let html = copy.html.filter(|html| html.len() <= LARGEST_TEXT);
        (kind, text.to_owned(), html, None)
    };
    Some(NewClipboardItem {
        fingerprint: fingerprint(kind, &text, png.as_deref()),
        kind,
        text,
        html,
        image_png: png,
        source_name: copy.source_name,
        source_bundle: copy.source_bundle,
    })
}

fn is_private(copy: &Copy) -> bool {
    copy.types.iter().any(|kind| PRIVATE_MARKERS.contains(&kind.as_str()))
        || copy.source_bundle.as_deref().is_some_and(|bundle| PRIVATE_APPS.contains(&bundle))
}

/// A web address and nothing else.
fn is_link(text: &str) -> bool {
    let text = text.trim();
    (text.starts_with("https://") || text.starts_with("http://")) && !text.contains(char::is_whitespace)
}

fn fingerprint(kind: ClipboardKind, text: &str, png: Option<&[u8]>) -> String {
    let mut hash = Sha256::new();
    hash.update(format!("{kind:?}").as_bytes());
    hash.update([0]);
    hash.update(text.as_bytes());
    hash.update([0]);
    hash.update(png.unwrap_or_default());
    format!("{:x}", hash.finalize())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn copied(text: &str) -> Copy {
        Copy {
            types: vec!["public.utf8-plain-text".to_owned()],
            text: Some(text.to_owned()),
            source_name: Some("Safari".to_owned()),
            source_bundle: Some("com.apple.Safari".to_owned()),
            ..Copy::default()
        }
    }

    #[test]
    fn text_is_kept_with_its_rich_version_and_its_source() {
        let item = to_item(Copy { html: Some("<b>Hi</b>".to_owned()), ..copied("Hi") }).expect("kept");
        assert_eq!(item.kind, ClipboardKind::Text);
        assert_eq!(item.text, "Hi");
        assert_eq!(item.html.as_deref(), Some("<b>Hi</b>"));
        assert_eq!(item.source_name.as_deref(), Some("Safari"));
    }

    #[test]
    fn a_web_address_alone_is_a_link() {
        assert_eq!(to_item(copied(" https://example.com/a?b=1 ")).map(|item| item.kind), Some(ClipboardKind::Link));
        assert_eq!(to_item(copied("see https://example.com")).map(|item| item.kind), Some(ClipboardKind::Text));
    }

    #[test]
    fn a_copied_image_stays_an_image_even_with_its_address_as_text() {
        let image = Copy { png: Some(vec![1, 2, 3]), ..copied("https://example.com/cat.png") };
        let item = to_item(image).expect("kept");
        assert_eq!(item.kind, ClipboardKind::Image);
        assert_eq!(item.image_png, Some(vec![1, 2, 3]));
        assert!(item.text.is_empty());
    }

    #[test]
    fn copied_files_are_kept_as_their_paths() {
        let files = Copy { files: vec!["/Users/me/a.pdf".to_owned(), "/Users/me/b.png".to_owned()], ..copied("a.pdf") };
        let item = to_item(files).expect("kept");
        assert_eq!(item.kind, ClipboardKind::Files);
        assert_eq!(item.text, "/Users/me/a.pdf\n/Users/me/b.png");
    }

    #[test]
    fn passwords_are_never_kept() {
        let marked = Copy { types: vec!["org.nspasteboard.ConcealedType".to_owned()], ..copied("hunter2") };
        assert_eq!(to_item(marked), None);
        let from_password_app = Copy { source_bundle: Some("com.1password.1password".to_owned()), ..copied("hunter2") };
        assert_eq!(to_item(from_password_app), None);
    }

    #[test]
    fn empty_and_oversized_copies_are_left_out() {
        assert_eq!(to_item(copied("   \n")), None);
        assert_eq!(to_item(copied(&"x".repeat(LARGEST_TEXT + 1))), None);
    }

    #[test]
    fn the_same_content_has_the_same_fingerprint_whoever_copied_it() {
        let from_safari = to_item(copied("same")).expect("kept");
        let from_notes = to_item(Copy { source_bundle: Some("com.apple.Notes".to_owned()), ..copied("same") }).expect("kept");
        assert_eq!(from_safari.fingerprint, from_notes.fingerprint);
        assert_ne!(from_safari.fingerprint, to_item(copied("other")).expect("kept").fingerprint);
    }
}
